Repository StakeNow/SIWT, pull requests merged in 2023-07, with the labels that each got.

#34 Fix/refactor_fa2_compat
  package-lock.json
  package.json
  packages/smart-contracts/README.md
  packages/smart-contracts/src/ligo/src/common/errors.jsligo
  packages/smart-contracts/src/ligo/src/core/balance_of.jsligo
  packages/smart-contracts/src/ligo/src/core/errors.jsligo
  packages/smart-contracts/src/ligo/src/core/ledger.jsligo
  packages/smart-contracts/src/ligo/src/core/operators.jsligo
  packages/smart-contracts/src/ligo/src/core/storage.jsligo
  packages/smart-contracts/src/ligo/src/core/transfer.jsligo
  packages/smart-contracts/src/ligo/src/core/update_operators.jsligo
  packages/smart-contracts/src/ligo/src/fa2_core.jsligo
  packages/smart-contracts/src/ligo/src/policy_manager.jsligo
Labels: bug

#40 Feat/check message validity
  package-lock.json
  package.json
  packages/discord/src/app/modules/api/api.ts
  packages/docs.siwt.xyz/docs/getting-started/putting-it-together.md
  packages/docs.siwt.xyz/docs/getting-started/server.md
  packages/sdk/src/lib/constants/index.ts
  packages/sdk/src/lib/types/index.ts
  packages/sdk/src/lib/utils.spec.ts
  packages/sdk/src/lib/utils.ts
  packages/sdk/src/lib/utils/index.ts
  packages/sdk/src/lib/utils/utils.spec.ts
  packages/sdk/src/lib/utils/utils.ts
  packages/siwt.xyz/common/siwt/siwt.ts
  packages/siwt.xyz/components/Try/Try.tsx
Labels: bug, enhancement

#41 Prepare release
  packages/acq/package.json
  packages/core/package.json
  packages/react/package.json
  packages/sdk/package.json
Labels: documentation
