Repository StakeNow/SIWT, pull requests merged in 2023-03, with the labels that each got.

#8 Review documentation
  README.md
  packages/acq/README.md
  packages/core/README.md
  packages/discord-bot-ui/README.md
  packages/discord/README.md
  packages/docs.siwt.xyz/docs/access-control-query.md
  packages/docs.siwt.xyz/docs/core.md
  packages/docs.siwt.xyz/docs/discord-bot/intro.md
  packages/docs.siwt.xyz/docs/discord-bot/server.md
  packages/docs.siwt.xyz/docs/discord-bot/ui.md
  packages/docs.siwt.xyz/docs/getting-started/putting-it-together.md
  packages/docs.siwt.xyz/docs/getting-started/server.md
  packages/docs.siwt.xyz/docs/getting-started/ui.md
  packages/docs.siwt.xyz/docs/intro.md
  packages/docs.siwt.xyz/docs/sdk.md
  packages/react/README.md
  packages/sdk/README.md
Labels: documentation

#9 Doc/CI: General project improvements
  .github/workflows/spdx.yml
  README.md
  packages/docs.siwt.xyz/docusaurus.config.js
Labels: documentation, enhancement

#17 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#19 version bump to 0.0.3
  packages/core/package.json
  packages/react/package.json
  packages/sdk/package.json
Labels: documentation

#20 added explanation for versioning to the docs + minor edits
  packages/docs.siwt.xyz/docs/intro.md
Labels: documentation

#21 Prepare for release
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/release-packages.yml
  packages/core/package.json
  packages/docs.siwt.xyz/docs/intro.md
  packages/react/package.json
  packages/sdk/package.json
Labels: enhancement
